name: fastapi_app

services:
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-cloud}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-cloud}
      POSTGRES_DB: ${POSTGRES_DB:-db}
    ports:
      - "5432:5432"

  app:
    image: theodecourt/fast_app-app:latest
    container_name: fastapi_app
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER:-cloud}:${POSTGRES_PASSWORD:-cloud}@db:5432/${POSTGRES_DB:-db}"
      SECRET_KEY_JWT: ${SECRET_KEY_JWT:-j&4*F7j3l!2Nf4#skl09@3nl1nj&BHJKNJKDNAn&8#3G@Hsj}
    ports:
      - "8000:8000"
    depends_on:
      - db
